name: enkornese
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^1.1.1
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.5.0
  cloud_firestore: ^0.13.1
  firebase_image: ^0.1.6
  firebase_database: ^3.1.1
  intl: ^0.16.1
  shared_preferences: ^0.5.8
  provider: ^4.3.1
  sticky_headers: ^0.1.8+1
  flutter_tts: ^1.2.2
  share: ^0.6.3+5
  google_fonts: ^0.3.9
  substring_highlight: ^0.1.2
  fluttertoast: ^3.1.3
  material_design_icons_flutter: ^4.0.5045
  cache_image: "^1.0.5"
  animated_text_kit: ^2.0.0
  demoji: ^1.0.1
  splashscreen:
  paginate_firestore: 0.1.1+1
  buttons_tabbar: ^0.1.1+1
  expansion_card: ^0.1.0
  expansion_tile_card: ^1.1.0
  flutter_neumorphic: ^3.0.1
  slide_popup_dialog: ^0.0.2
  http:
  youtube_player_flutter: ^7.0.0+7
  get: ^3.4.6
  flutter_widget_from_html: ^0.4.1
  carousel_slider: ^2.2.1
  getwidget: ^1.1.0
  characters: ^1.0.0
  flutter_svg: ^0.18.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
 
dev_dependencies:
  flutter_test:
    sdk: flutter

#  following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
   - images/01.png
   - images/02.png
   - images/korea.png
   - images/japan.png
   - images/usa.png
   - images/china.png
   - images/vietnam.png
   - images/germany.png
   - images/pokeball.png
   - images/hawaii.jpg
   - images/013.jpg
   - images/flutter_onboarding_1.png
   - images/flutter_onboarding_2.png
   - images/flutter_onboarding_3.png
   - images/flutter_onboarding_4.png
   - images/enklogo.png
   - images/mustknow.png
   - images/girl1.jpg
   - images/girl2.jpg
   - images/girl3.jpg
   - images/girl4.jpg
   - images/girl5.jpg
   - images/girl6.jpg

  fonts:
     - family: Montserrat
       fonts:
          - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
            style: italic
          - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
            weight: 700
          - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
            weight: 500
          - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
            weight: 300
     - family: NotoSansCJKkr
       fonts:
          - asset: assets/fonts/NotoSansCJKkr/NotoSansCJKkr-Bold.otf
          - asset: assets/fonts/NotoSansCJKkr/NotoSansCJKkr-Light.otf
          - asset: assets/fonts/NotoSansCJKkr/NotoSansCJKkr-Regular.otf
# fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages  